import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import { cn } from "@/lib/utils";
import "@/app/globals.css";
import Header from "@/app/header";
import { KnockProviders } from "./knock-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProvider>
          <KnockProviders>
            <Header />
            <div className="container mx-auto py-12">{children}</div>
          </KnockProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
